apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-lnbs
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/bootstrap/integration-e2e-tenant/integ-app-ptpp/devfile-sample-python-basic-lnbs@sha256:7f2dec96c98eb77984188689a46b69ed967cc18d4e28cf1a5165403c3bc57595
        name: my-python
        resources: {}
status: {}
